export const INITIALIZE_API_CHANEL = 'INITIALIZE_API_CHANEL';
export const INITIALIZE_API_CHANEL_START = 'INITIALIZE_API_CHANEL_START';
export const INITIALIZE_API_CHANEL_DONE = 'INITIALIZE_API_CHANEL_DONE';
export const INITIALIZE_API_CHANEL_ERROR = 'INITIALIZE_API_CHANEL_ERROR';