export const MAIN_THREAD_CHANNEL = 'MAIN_THREAD_CHANNEL';
export const INIT_API = 'INIT_API';
export const INIT_API_START = 'INIT_API_START';
export const INIT_API_DONE = 'INIT_API_DONE';
export const INIT_API_ERROR = 'INIT_API_ERROR';
export const ACTIVATE_WINDOW = 'ACTIVATE_WINDOW';
export const SET_TRAY = 'SET_TRAY';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';